>P1;4hpg.pdb

-------------------------------------VGVCYGMQGNNLPPVSEVIALYK
KSNITRMRIYDPNQAVLEALRGSNIELILGVPNSDLQSLTNPSNAKSWVQKNVRGFWSSV
RFRYIAVGNEISPVNRGTAWLAQFVLPAMRNIHDAIRSAGLQDQIKVSTAIDLTLVGNSY
PPSAGAFRDDVRSYLNPIIRFLSSIRSPLLANIYPYFTYAGNPRDISLPYALFTSPSVVV
WDGQRGYKNLFDATLDALYSALERASGGSLEVVVSESGWPSAGAFAATFDNGRTYLSNLI
QHVKRGTPKRPKRAIETYLFAMFDENKKQPEVEKHFGLFFPNKWQKYNLNFS--------
--------------
*
>P1;sp|P52407|E13B_HEVBR

MAISSSTSGTSSSFPSRTTVMLLLFFFAASVGITDAQVGVCYGMQGNNLPPVSEVIALYK
KSNITRMRIYDPNRAVLEALRGSNIELILGVPNSDLQSLTNPSNAKSWVQKNVRGFWSSV
LFRYIAVGNEISPVNRGTAWLAQFVLPAMRNIHDAIRSAGLQDQIKVSTAIDLTLVGNSY
PPSAGAFRDDVRSYLDPIIGFLSSIRSPLLANIYPYFTYAYNPRDISLPYALFTSPSVVV
WDGQRGYKNLFDATLDALYSALERASGGSLEVVVSESGWPSAGAFAATFDNGRTYLSNLI
QHVKGGTPKRPNRAIETYLFAMFDENKKQPEVEKHFGLFFPNKWQKYNLNFSAEKNWDIS
TEHNATILFLKSDM
*
