# Generated by Django 3.0.5 on 2020-10-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretorio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('extensao', models.CharField(max_length=255)),
                ('diretorio_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Modelos')),
            ],
        ),
    ]
