# Generated by Django 3.0.5 on 2020-08-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('cabecalho', models.CharField(max_length=255)),
                ('sequencia', models.TextField()),
            ],
        ),
    ]
